name: 'dotenv'
description: 'Load variables from .env file'
inputs:
  path:  # id of input
    description: 'the path to the .env file (including file name)'
    required: true
    default: '.env'
outputs:
  generic: # output will be available to future steps 
    description: 'This command will have generic output variables based on .env'
runs:
  using: 'node12'
  main: 'dist/index.js'
